version: "3.7"

services:
  development:
    image: serverless/service-development
    restart: always
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: deploy/nodejs/Dockerfile
      cache_from:
        - serverless
      args:
        - RUN_NPM_INSTALL=false
    env_file:
      - deploy/env/development
    volumes:
      - .:/www
